//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAV.Portfolio {
    
    
    public partial class SwitchHistory {
        
        /// <summary>
        /// ucHeader1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NAV.Portfolio.UserControl.ucHeader ucHeader1;
        
        /// <summary>
        /// ucCurrentPortfolio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NAV.Portfolio.UserControl.ucCurrentPortfolio ucCurrentPortfolio;
        
        /// <summary>
        /// divHistoryHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divHistoryHolder;
    }
}
