//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAV.Scheme {
    
    
    public partial class SchemeClient {
        
        /// <summary>
        /// lbtnHistory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbtnHistory;
        
        /// <summary>
        /// ucHeader1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NAV.Scheme.UserControl.ucHeader ucHeader1;
        
        /// <summary>
        /// ucCurrentHoldings1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NAV.Scheme.UserControl.ucCurrentHoldings ucCurrentHoldings1;
        
        /// <summary>
        /// ucContributions1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NAV.Scheme.UserControl.ucContributions ucContributions1;
        
        /// <summary>
        /// ucProposalDisplay1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NAV.Scheme.UserControl.ucProposalDisplay ucProposalDisplay1;
        
        /// <summary>
        /// ucProposalDisplay2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NAV.Scheme.UserControl.ucProposalDisplay ucProposalDisplay2;
        
        /// <summary>
        /// ucSwitchDetailsClient1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NAV.Scheme.UserControl.ucSwitchDetailsClient ucSwitchDetailsClient1;
    }
}
